sudo: required
services:
  - docker

before_install:
  - docker build -t g245/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run g245/react-test npm test -- --coverage

after_success:
  - docker build -t g245/multi-client ./client
  - docker build -t g245/multi-nginx ./nginx
  - docker build -t g245/multi-server ./server
  - docker build -t g245/multi-worker ./worker
  # Login in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push build image to dockerhub
  - docker push g245/multi-client
  - docker push g245/multi-nginx
  - docker push g245/multi-server
  - docker push g245/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: muti-container
  env: MutiContainer-env
  bucket_name: elasticbeanstalk-us-east-1-314735444478
  bucket_path: multi-container
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY





  
